#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 84
#define LARGE_STATE_COUNT 23
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 6

enum ts_symbol_identifiers {
  sym__symchars = 1,
  sym__ws = 2,
  anon_sym_POUND = 3,
  aux_sym_comment_token1 = 4,
  anon_sym_nil = 5,
  anon_sym_true = 6,
  anon_sym_false = 7,
  aux_sym_constant_token1 = 8,
  sym_number = 9,
  sym_keyword = 10,
  anon_sym_AT = 11,
  anon_sym_LPAREN = 12,
  anon_sym_RPAREN = 13,
  anon_sym_LBRACK = 14,
  anon_sym_RBRACK = 15,
  anon_sym_LBRACE = 16,
  anon_sym_RBRACE = 17,
  sym_symbol = 18,
  sym_hex = 19,
  aux_sym_escape_token1 = 20,
  aux_sym_escape_token2 = 21,
  aux_sym_escape_token3 = 22,
  aux_sym_escape_token4 = 23,
  aux_sym_escape_token5 = 24,
  anon_sym_DQUOTE = 25,
  aux_sym_bytes_token1 = 26,
  sym_readermac = 27,
  sym_source_file = 28,
  sym_value = 29,
  sym_mvalue = 30,
  sym__raw_value = 31,
  sym__mraw_value = 32,
  sym_comment = 33,
  sym_constant = 34,
  sym_string = 35,
  sym_buffer = 36,
  sym_parray = 37,
  sym_barray = 38,
  sym_mptuple = 39,
  sym_ptuple = 40,
  sym_btuple = 41,
  sym_struct = 42,
  sym_dict = 43,
  sym_escape = 44,
  sym_bytes = 45,
  aux_sym_source_file_repeat1 = 46,
  aux_sym_value_repeat1 = 47,
  aux_sym_value_repeat2 = 48,
  aux_sym_mptuple_repeat1 = 49,
  aux_sym_mptuple_repeat2 = 50,
  aux_sym_struct_repeat1 = 51,
  aux_sym_bytes_repeat1 = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__symchars] = "_symchars",
  [sym__ws] = "_ws",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_nil] = "nil",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [aux_sym_constant_token1] = "constant_token1",
  [sym_number] = "number",
  [sym_keyword] = "keyword",
  [anon_sym_AT] = "@",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_symbol] = "symbol",
  [sym_hex] = "hex",
  [aux_sym_escape_token1] = "escape_token1",
  [aux_sym_escape_token2] = "escape_token2",
  [aux_sym_escape_token3] = "escape_token3",
  [aux_sym_escape_token4] = "escape_token4",
  [aux_sym_escape_token5] = "escape_token5",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_bytes_token1] = "bytes_token1",
  [sym_readermac] = "readermac",
  [sym_source_file] = "source_file",
  [sym_value] = "value",
  [sym_mvalue] = "mvalue",
  [sym__raw_value] = "_raw_value",
  [sym__mraw_value] = "_mraw_value",
  [sym_comment] = "comment",
  [sym_constant] = "constant",
  [sym_string] = "string",
  [sym_buffer] = "buffer",
  [sym_parray] = "parray",
  [sym_barray] = "barray",
  [sym_mptuple] = "mptuple",
  [sym_ptuple] = "ptuple",
  [sym_btuple] = "btuple",
  [sym_struct] = "struct",
  [sym_dict] = "dict",
  [sym_escape] = "escape",
  [sym_bytes] = "bytes",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_value_repeat1] = "value_repeat1",
  [aux_sym_value_repeat2] = "value_repeat2",
  [aux_sym_mptuple_repeat1] = "mptuple_repeat1",
  [aux_sym_mptuple_repeat2] = "mptuple_repeat2",
  [aux_sym_struct_repeat1] = "struct_repeat1",
  [aux_sym_bytes_repeat1] = "bytes_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__symchars] = sym__symchars,
  [sym__ws] = sym__ws,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_nil] = anon_sym_nil,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [aux_sym_constant_token1] = aux_sym_constant_token1,
  [sym_number] = sym_number,
  [sym_keyword] = sym_keyword,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_symbol] = sym_symbol,
  [sym_hex] = sym_hex,
  [aux_sym_escape_token1] = aux_sym_escape_token1,
  [aux_sym_escape_token2] = aux_sym_escape_token2,
  [aux_sym_escape_token3] = aux_sym_escape_token3,
  [aux_sym_escape_token4] = aux_sym_escape_token4,
  [aux_sym_escape_token5] = aux_sym_escape_token5,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_bytes_token1] = aux_sym_bytes_token1,
  [sym_readermac] = sym_readermac,
  [sym_source_file] = sym_source_file,
  [sym_value] = sym_value,
  [sym_mvalue] = sym_mvalue,
  [sym__raw_value] = sym__raw_value,
  [sym__mraw_value] = sym__mraw_value,
  [sym_comment] = sym_comment,
  [sym_constant] = sym_constant,
  [sym_string] = sym_string,
  [sym_buffer] = sym_buffer,
  [sym_parray] = sym_parray,
  [sym_barray] = sym_barray,
  [sym_mptuple] = sym_mptuple,
  [sym_ptuple] = sym_ptuple,
  [sym_btuple] = sym_btuple,
  [sym_struct] = sym_struct,
  [sym_dict] = sym_dict,
  [sym_escape] = sym_escape,
  [sym_bytes] = sym_bytes,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_value_repeat1] = aux_sym_value_repeat1,
  [aux_sym_value_repeat2] = aux_sym_value_repeat2,
  [aux_sym_mptuple_repeat1] = aux_sym_mptuple_repeat1,
  [aux_sym_mptuple_repeat2] = aux_sym_mptuple_repeat2,
  [aux_sym_struct_repeat1] = aux_sym_struct_repeat1,
  [aux_sym_bytes_repeat1] = aux_sym_bytes_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__symchars] = {
    .visible = false,
    .named = true,
  },
  [sym__ws] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_nil] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_constant_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_hex] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_escape_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_token5] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_bytes_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_readermac] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_mvalue] = {
    .visible = true,
    .named = true,
  },
  [sym__raw_value] = {
    .visible = false,
    .named = true,
  },
  [sym__mraw_value] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_buffer] = {
    .visible = true,
    .named = true,
  },
  [sym_parray] = {
    .visible = true,
    .named = true,
  },
  [sym_barray] = {
    .visible = true,
    .named = true,
  },
  [sym_mptuple] = {
    .visible = true,
    .named = true,
  },
  [sym_ptuple] = {
    .visible = true,
    .named = true,
  },
  [sym_btuple] = {
    .visible = true,
    .named = true,
  },
  [sym_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_dict] = {
    .visible = true,
    .named = true,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_bytes] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_mptuple_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_mptuple_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bytes_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_exp = 1,
  field_mac = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_exp] = "exp",
  [field_mac] = "mac",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_mac, 0},
  [1] =
    {field_mac, 0, .inherited = true},
  [2] =
    {field_mac, 0, .inherited = true},
    {field_mac, 1, .inherited = true},
  [4] =
    {field_exp, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [5] = {
    [0] = sym_mptuple,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_ptuple, 2,
    sym_ptuple,
    sym_mptuple,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 3,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 17,
  [19] = 19,
  [20] = 17,
  [21] = 17,
  [22] = 17,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 49,
  [51] = 49,
  [52] = 49,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 49,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        0x07, 44,
        '"', 45,
        '#', 11,
        '(', 22,
        ')', 23,
        ',', 41,
        ':', 20,
        '@', 21,
        '[', 24,
        '\\', 43,
        ']', 25,
        '{', 26,
        '}', 27,
        '\'', 47,
        ';', 47,
        '|', 47,
        '~', 47,
        '0', 41,
        'b', 41,
        'e', 41,
        'f', 41,
        '?', 41,
        'n', 41,
        'r', 41,
        't', 41,
        'v', 41,
        'z', 41,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(10);
      if (('1' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'd')) ADVANCE(41);
      if (('!' <= lookahead && lookahead <= '_') ||
          ('g' <= lookahead && lookahead <= 'y') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        0x07, 44,
        '0', 44,
        '?', 44,
        'b', 44,
        'e', 44,
        'f', 44,
        'n', 44,
        'r', 44,
        't', 44,
        'v', 44,
        'z', 44,
      );
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'y') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(48);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 45,
        '#', 11,
        '(', 22,
        ')', 23,
        ',', 41,
        '.', 39,
        ':', 20,
        '@', 21,
        '[', 24,
        'f', 29,
        'n', 32,
        't', 35,
        '{', 26,
        '+', 28,
        '-', 28,
        '\'', 16,
        ';', 16,
        '|', 16,
        '~', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('!' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '"', 45,
        '#', 11,
        '(', 22,
        ',', 41,
        '.', 39,
        ':', 20,
        '@', 21,
        '[', 24,
        ']', 25,
        'f', 29,
        'n', 32,
        't', 35,
        '{', 26,
        '+', 28,
        '-', 28,
        '\'', 16,
        ';', 16,
        '|', 16,
        '~', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('!' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '"', 45,
        '#', 11,
        '(', 22,
        ',', 41,
        '.', 39,
        ':', 20,
        '@', 21,
        '[', 24,
        'f', 29,
        'n', 32,
        't', 35,
        '{', 26,
        '}', 27,
        '+', 28,
        '-', 28,
        '\'', 16,
        ';', 16,
        '|', 16,
        '~', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('!' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(45);
      if (lookahead == '\\') ADVANCE(43);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 6:
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == '\'' ||
          lookahead == ',' ||
          lookahead == ';' ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(42);
      END_STATE();
    case 7:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '"', 45,
        '#', 11,
        '(', 22,
        ')', 23,
        ',', 41,
        '.', 39,
        ':', 20,
        '@', 21,
        '[', 24,
        ']', 25,
        'f', 29,
        'n', 32,
        't', 35,
        '{', 26,
        '}', 27,
        '+', 28,
        '-', 28,
        '\'', 47,
        ';', 47,
        '|', 47,
        '~', 47,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('!' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '"', 45,
        '#', 11,
        '(', 22,
        ',', 41,
        '.', 39,
        ':', 20,
        '@', 21,
        '[', 24,
        'f', 29,
        'n', 32,
        't', 35,
        '{', 26,
        '+', 28,
        '-', 28,
        '\'', 16,
        ';', 16,
        '|', 16,
        '~', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('!' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym__ws);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_nil);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_constant_token1);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(39);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_keyword);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_AT);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '.') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'a') ADVANCE(33);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'e') ADVANCE(14);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'e') ADVANCE(15);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'i') ADVANCE(34);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'l') ADVANCE(36);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'l') ADVANCE(13);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'r') ADVANCE(37);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 's') ADVANCE(31);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'u') ADVANCE(30);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= 'Z') ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xff)) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_hex);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_escape_token1);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_escape_token2);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_bytes_token1);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_readermac);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym__symchars);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'U') ADVANCE(1);
      if (lookahead == 'u') ADVANCE(2);
      if (lookahead == 'x') ADVANCE(3);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(aux_sym_escape_token5);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(aux_sym_escape_token4);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(aux_sym_escape_token3);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 7},
  [2] = {.lex_state = 7},
  [3] = {.lex_state = 7},
  [4] = {.lex_state = 7},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 7},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 7},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 7},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 7},
  [14] = {.lex_state = 7},
  [15] = {.lex_state = 7},
  [16] = {.lex_state = 7},
  [17] = {.lex_state = 7},
  [18] = {.lex_state = 7},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 7},
  [21] = {.lex_state = 7},
  [22] = {.lex_state = 7},
  [23] = {.lex_state = 7},
  [24] = {.lex_state = 7},
  [25] = {.lex_state = 7},
  [26] = {.lex_state = 7},
  [27] = {.lex_state = 7},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 7},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 7},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 7},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 7},
  [37] = {.lex_state = 7},
  [38] = {.lex_state = 7},
  [39] = {.lex_state = 7},
  [40] = {.lex_state = 7},
  [41] = {.lex_state = 7},
  [42] = {.lex_state = 7},
  [43] = {.lex_state = 7},
  [44] = {.lex_state = 7},
  [45] = {.lex_state = 7},
  [46] = {.lex_state = 7},
  [47] = {.lex_state = 7},
  [48] = {.lex_state = 7},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 4},
  [52] = {.lex_state = 8},
  [53] = {.lex_state = 7},
  [54] = {.lex_state = 7},
  [55] = {.lex_state = 7},
  [56] = {.lex_state = 8},
  [57] = {.lex_state = 7},
  [58] = {.lex_state = 7},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 5},
  [61] = {.lex_state = 5},
  [62] = {.lex_state = 5},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 5},
  [65] = {.lex_state = 5},
  [66] = {.lex_state = 5},
  [67] = {.lex_state = 6},
  [68] = {.lex_state = 5},
  [69] = {.lex_state = 6},
  [70] = {.lex_state = 6},
  [71] = {.lex_state = 6},
  [72] = {.lex_state = 6},
  [73] = {.lex_state = 6},
  [74] = {.lex_state = 6},
  [75] = {.lex_state = 6},
  [76] = {.lex_state = 6},
  [77] = {.lex_state = 6},
  [78] = {.lex_state = 12},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 6},
  [81] = {.lex_state = 6},
  [82] = {.lex_state = 6},
  [83] = {.lex_state = 6},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__symchars] = ACTIONS(1),
    [sym__ws] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_keyword] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
    [sym_hex] = ACTIONS(1),
    [aux_sym_escape_token1] = ACTIONS(1),
    [aux_sym_escape_token2] = ACTIONS(1),
    [aux_sym_escape_token3] = ACTIONS(1),
    [aux_sym_escape_token4] = ACTIONS(1),
    [aux_sym_escape_token5] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_readermac] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(79),
    [sym_value] = STATE(13),
    [sym__raw_value] = STATE(26),
    [sym_comment] = STATE(26),
    [sym_constant] = STATE(26),
    [sym_string] = STATE(26),
    [sym_buffer] = STATE(26),
    [sym_parray] = STATE(26),
    [sym_barray] = STATE(26),
    [sym_mptuple] = STATE(26),
    [sym_ptuple] = STATE(26),
    [sym_btuple] = STATE(26),
    [sym_struct] = STATE(26),
    [sym_dict] = STATE(26),
    [sym_bytes] = STATE(39),
    [aux_sym_source_file_repeat1] = STATE(13),
    [aux_sym_value_repeat1] = STATE(17),
    [aux_sym_mptuple_repeat1] = STATE(69),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_nil] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(9),
    [anon_sym_false] = ACTIONS(9),
    [sym_number] = ACTIONS(11),
    [sym_keyword] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
    [sym_symbol] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [sym_readermac] = ACTIONS(25),
  },
  [2] = {
    [sym_value] = STATE(16),
    [sym__raw_value] = STATE(26),
    [sym_comment] = STATE(26),
    [sym_constant] = STATE(26),
    [sym_string] = STATE(26),
    [sym_buffer] = STATE(26),
    [sym_parray] = STATE(26),
    [sym_barray] = STATE(26),
    [sym_mptuple] = STATE(26),
    [sym_ptuple] = STATE(26),
    [sym_btuple] = STATE(26),
    [sym_struct] = STATE(26),
    [sym_dict] = STATE(26),
    [sym_bytes] = STATE(39),
    [aux_sym_value_repeat1] = STATE(18),
    [aux_sym_mptuple_repeat1] = STATE(69),
    [aux_sym_struct_repeat1] = STATE(7),
    [sym__ws] = ACTIONS(27),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_nil] = ACTIONS(29),
    [anon_sym_true] = ACTIONS(29),
    [anon_sym_false] = ACTIONS(29),
    [sym_number] = ACTIONS(11),
    [sym_keyword] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
    [anon_sym_RBRACE] = ACTIONS(31),
    [sym_symbol] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [sym_readermac] = ACTIONS(25),
  },
  [3] = {
    [sym_value] = STATE(3),
    [sym__raw_value] = STATE(26),
    [sym_comment] = STATE(26),
    [sym_constant] = STATE(26),
    [sym_string] = STATE(26),
    [sym_buffer] = STATE(26),
    [sym_parray] = STATE(26),
    [sym_barray] = STATE(26),
    [sym_mptuple] = STATE(26),
    [sym_ptuple] = STATE(26),
    [sym_btuple] = STATE(26),
    [sym_struct] = STATE(26),
    [sym_dict] = STATE(26),
    [sym_bytes] = STATE(39),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_value_repeat1] = STATE(17),
    [aux_sym_mptuple_repeat1] = STATE(69),
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym__ws] = ACTIONS(35),
    [anon_sym_POUND] = ACTIONS(38),
    [anon_sym_nil] = ACTIONS(41),
    [anon_sym_true] = ACTIONS(41),
    [anon_sym_false] = ACTIONS(41),
    [sym_number] = ACTIONS(44),
    [sym_keyword] = ACTIONS(47),
    [anon_sym_AT] = ACTIONS(50),
    [anon_sym_LPAREN] = ACTIONS(53),
    [anon_sym_LBRACK] = ACTIONS(56),
    [anon_sym_LBRACE] = ACTIONS(59),
    [sym_symbol] = ACTIONS(44),
    [anon_sym_DQUOTE] = ACTIONS(62),
    [sym_readermac] = ACTIONS(65),
  },
  [4] = {
    [sym_value] = STATE(4),
    [sym__raw_value] = STATE(26),
    [sym_comment] = STATE(26),
    [sym_constant] = STATE(26),
    [sym_string] = STATE(26),
    [sym_buffer] = STATE(26),
    [sym_parray] = STATE(26),
    [sym_barray] = STATE(26),
    [sym_mptuple] = STATE(26),
    [sym_ptuple] = STATE(26),
    [sym_btuple] = STATE(26),
    [sym_struct] = STATE(26),
    [sym_dict] = STATE(26),
    [sym_bytes] = STATE(39),
    [aux_sym_source_file_repeat1] = STATE(4),
    [aux_sym_value_repeat1] = STATE(22),
    [aux_sym_mptuple_repeat1] = STATE(69),
    [sym__ws] = ACTIONS(68),
    [anon_sym_POUND] = ACTIONS(38),
    [anon_sym_nil] = ACTIONS(71),
    [anon_sym_true] = ACTIONS(71),
    [anon_sym_false] = ACTIONS(71),
    [sym_number] = ACTIONS(44),
    [sym_keyword] = ACTIONS(47),
    [anon_sym_AT] = ACTIONS(50),
    [anon_sym_LPAREN] = ACTIONS(53),
    [anon_sym_LBRACK] = ACTIONS(56),
    [anon_sym_RBRACK] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(59),
    [sym_symbol] = ACTIONS(44),
    [anon_sym_DQUOTE] = ACTIONS(62),
    [sym_readermac] = ACTIONS(65),
  },
  [5] = {
    [sym_value] = STATE(11),
    [sym__raw_value] = STATE(26),
    [sym_comment] = STATE(26),
    [sym_constant] = STATE(26),
    [sym_string] = STATE(26),
    [sym_buffer] = STATE(26),
    [sym_parray] = STATE(26),
    [sym_barray] = STATE(26),
    [sym_mptuple] = STATE(26),
    [sym_ptuple] = STATE(26),
    [sym_btuple] = STATE(26),
    [sym_struct] = STATE(26),
    [sym_dict] = STATE(26),
    [sym_bytes] = STATE(39),
    [aux_sym_source_file_repeat1] = STATE(11),
    [aux_sym_value_repeat1] = STATE(21),
    [aux_sym_mptuple_repeat1] = STATE(69),
    [sym__ws] = ACTIONS(74),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_nil] = ACTIONS(76),
    [anon_sym_true] = ACTIONS(76),
    [anon_sym_false] = ACTIONS(76),
    [sym_number] = ACTIONS(11),
    [sym_keyword] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(78),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
    [sym_symbol] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [sym_readermac] = ACTIONS(25),
  },
  [6] = {
    [sym_value] = STATE(8),
    [sym__raw_value] = STATE(26),
    [sym_comment] = STATE(26),
    [sym_constant] = STATE(26),
    [sym_string] = STATE(26),
    [sym_buffer] = STATE(26),
    [sym_parray] = STATE(26),
    [sym_barray] = STATE(26),
    [sym_mptuple] = STATE(26),
    [sym_ptuple] = STATE(26),
    [sym_btuple] = STATE(26),
    [sym_struct] = STATE(26),
    [sym_dict] = STATE(26),
    [sym_bytes] = STATE(39),
    [aux_sym_source_file_repeat1] = STATE(8),
    [aux_sym_value_repeat1] = STATE(22),
    [aux_sym_mptuple_repeat1] = STATE(69),
    [sym__ws] = ACTIONS(80),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_nil] = ACTIONS(82),
    [anon_sym_true] = ACTIONS(82),
    [anon_sym_false] = ACTIONS(82),
    [sym_number] = ACTIONS(11),
    [sym_keyword] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_RBRACK] = ACTIONS(84),
    [anon_sym_LBRACE] = ACTIONS(21),
    [sym_symbol] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [sym_readermac] = ACTIONS(25),
  },
  [7] = {
    [sym_value] = STATE(16),
    [sym__raw_value] = STATE(26),
    [sym_comment] = STATE(26),
    [sym_constant] = STATE(26),
    [sym_string] = STATE(26),
    [sym_buffer] = STATE(26),
    [sym_parray] = STATE(26),
    [sym_barray] = STATE(26),
    [sym_mptuple] = STATE(26),
    [sym_ptuple] = STATE(26),
    [sym_btuple] = STATE(26),
    [sym_struct] = STATE(26),
    [sym_dict] = STATE(26),
    [sym_bytes] = STATE(39),
    [aux_sym_value_repeat1] = STATE(18),
    [aux_sym_mptuple_repeat1] = STATE(69),
    [aux_sym_struct_repeat1] = STATE(14),
    [sym__ws] = ACTIONS(27),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_nil] = ACTIONS(29),
    [anon_sym_true] = ACTIONS(29),
    [anon_sym_false] = ACTIONS(29),
    [sym_number] = ACTIONS(11),
    [sym_keyword] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
    [anon_sym_RBRACE] = ACTIONS(86),
    [sym_symbol] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [sym_readermac] = ACTIONS(25),
  },
  [8] = {
    [sym_value] = STATE(4),
    [sym__raw_value] = STATE(26),
    [sym_comment] = STATE(26),
    [sym_constant] = STATE(26),
    [sym_string] = STATE(26),
    [sym_buffer] = STATE(26),
    [sym_parray] = STATE(26),
    [sym_barray] = STATE(26),
    [sym_mptuple] = STATE(26),
    [sym_ptuple] = STATE(26),
    [sym_btuple] = STATE(26),
    [sym_struct] = STATE(26),
    [sym_dict] = STATE(26),
    [sym_bytes] = STATE(39),
    [aux_sym_source_file_repeat1] = STATE(4),
    [aux_sym_value_repeat1] = STATE(22),
    [aux_sym_mptuple_repeat1] = STATE(69),
    [sym__ws] = ACTIONS(80),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_nil] = ACTIONS(82),
    [anon_sym_true] = ACTIONS(82),
    [anon_sym_false] = ACTIONS(82),
    [sym_number] = ACTIONS(11),
    [sym_keyword] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_RBRACK] = ACTIONS(88),
    [anon_sym_LBRACE] = ACTIONS(21),
    [sym_symbol] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [sym_readermac] = ACTIONS(25),
  },
  [9] = {
    [sym_value] = STATE(9),
    [sym__raw_value] = STATE(26),
    [sym_comment] = STATE(26),
    [sym_constant] = STATE(26),
    [sym_string] = STATE(26),
    [sym_buffer] = STATE(26),
    [sym_parray] = STATE(26),
    [sym_barray] = STATE(26),
    [sym_mptuple] = STATE(26),
    [sym_ptuple] = STATE(26),
    [sym_btuple] = STATE(26),
    [sym_struct] = STATE(26),
    [sym_dict] = STATE(26),
    [sym_bytes] = STATE(39),
    [aux_sym_source_file_repeat1] = STATE(9),
    [aux_sym_value_repeat1] = STATE(21),
    [aux_sym_mptuple_repeat1] = STATE(69),
    [sym__ws] = ACTIONS(90),
    [anon_sym_POUND] = ACTIONS(38),
    [anon_sym_nil] = ACTIONS(93),
    [anon_sym_true] = ACTIONS(93),
    [anon_sym_false] = ACTIONS(93),
    [sym_number] = ACTIONS(44),
    [sym_keyword] = ACTIONS(47),
    [anon_sym_AT] = ACTIONS(50),
    [anon_sym_LPAREN] = ACTIONS(53),
    [anon_sym_RPAREN] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(56),
    [anon_sym_LBRACE] = ACTIONS(59),
    [sym_symbol] = ACTIONS(44),
    [anon_sym_DQUOTE] = ACTIONS(62),
    [sym_readermac] = ACTIONS(65),
  },
  [10] = {
    [sym_mvalue] = STATE(12),
    [sym__mraw_value] = STATE(47),
    [sym_comment] = STATE(47),
    [sym_constant] = STATE(47),
    [sym_string] = STATE(47),
    [sym_buffer] = STATE(47),
    [sym_parray] = STATE(47),
    [sym_barray] = STATE(47),
    [sym_mptuple] = STATE(47),
    [sym_ptuple] = STATE(54),
    [sym_btuple] = STATE(47),
    [sym_struct] = STATE(47),
    [sym_dict] = STATE(47),
    [sym_bytes] = STATE(39),
    [aux_sym_value_repeat1] = STATE(19),
    [aux_sym_mptuple_repeat1] = STATE(69),
    [aux_sym_mptuple_repeat2] = STATE(12),
    [sym__ws] = ACTIONS(96),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_nil] = ACTIONS(76),
    [anon_sym_true] = ACTIONS(76),
    [anon_sym_false] = ACTIONS(76),
    [sym_number] = ACTIONS(98),
    [sym_keyword] = ACTIONS(100),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(102),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
    [sym_symbol] = ACTIONS(98),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [sym_readermac] = ACTIONS(25),
  },
  [11] = {
    [sym_value] = STATE(9),
    [sym__raw_value] = STATE(26),
    [sym_comment] = STATE(26),
    [sym_constant] = STATE(26),
    [sym_string] = STATE(26),
    [sym_buffer] = STATE(26),
    [sym_parray] = STATE(26),
    [sym_barray] = STATE(26),
    [sym_mptuple] = STATE(26),
    [sym_ptuple] = STATE(26),
    [sym_btuple] = STATE(26),
    [sym_struct] = STATE(26),
    [sym_dict] = STATE(26),
    [sym_bytes] = STATE(39),
    [aux_sym_source_file_repeat1] = STATE(9),
    [aux_sym_value_repeat1] = STATE(21),
    [aux_sym_mptuple_repeat1] = STATE(69),
    [sym__ws] = ACTIONS(74),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_nil] = ACTIONS(76),
    [anon_sym_true] = ACTIONS(76),
    [anon_sym_false] = ACTIONS(76),
    [sym_number] = ACTIONS(11),
    [sym_keyword] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(104),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
    [sym_symbol] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [sym_readermac] = ACTIONS(25),
  },
  [12] = {
    [sym_mvalue] = STATE(12),
    [sym__mraw_value] = STATE(47),
    [sym_comment] = STATE(47),
    [sym_constant] = STATE(47),
    [sym_string] = STATE(47),
    [sym_buffer] = STATE(47),
    [sym_parray] = STATE(47),
    [sym_barray] = STATE(47),
    [sym_mptuple] = STATE(47),
    [sym_ptuple] = STATE(54),
    [sym_btuple] = STATE(47),
    [sym_struct] = STATE(47),
    [sym_dict] = STATE(47),
    [sym_bytes] = STATE(39),
    [aux_sym_value_repeat1] = STATE(19),
    [aux_sym_mptuple_repeat1] = STATE(69),
    [aux_sym_mptuple_repeat2] = STATE(12),
    [sym__ws] = ACTIONS(106),
    [anon_sym_POUND] = ACTIONS(109),
    [anon_sym_nil] = ACTIONS(112),
    [anon_sym_true] = ACTIONS(112),
    [anon_sym_false] = ACTIONS(112),
    [sym_number] = ACTIONS(115),
    [sym_keyword] = ACTIONS(118),
    [anon_sym_AT] = ACTIONS(121),
    [anon_sym_LPAREN] = ACTIONS(124),
    [anon_sym_RPAREN] = ACTIONS(127),
    [anon_sym_LBRACK] = ACTIONS(129),
    [anon_sym_LBRACE] = ACTIONS(132),
    [sym_symbol] = ACTIONS(115),
    [anon_sym_DQUOTE] = ACTIONS(135),
    [sym_readermac] = ACTIONS(138),
  },
  [13] = {
    [sym_value] = STATE(3),
    [sym__raw_value] = STATE(26),
    [sym_comment] = STATE(26),
    [sym_constant] = STATE(26),
    [sym_string] = STATE(26),
    [sym_buffer] = STATE(26),
    [sym_parray] = STATE(26),
    [sym_barray] = STATE(26),
    [sym_mptuple] = STATE(26),
    [sym_ptuple] = STATE(26),
    [sym_btuple] = STATE(26),
    [sym_struct] = STATE(26),
    [sym_dict] = STATE(26),
    [sym_bytes] = STATE(39),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_value_repeat1] = STATE(17),
    [aux_sym_mptuple_repeat1] = STATE(69),
    [ts_builtin_sym_end] = ACTIONS(141),
    [sym__ws] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_nil] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(9),
    [anon_sym_false] = ACTIONS(9),
    [sym_number] = ACTIONS(11),
    [sym_keyword] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
    [sym_symbol] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [sym_readermac] = ACTIONS(25),
  },
  [14] = {
    [sym_value] = STATE(16),
    [sym__raw_value] = STATE(26),
    [sym_comment] = STATE(26),
    [sym_constant] = STATE(26),
    [sym_string] = STATE(26),
    [sym_buffer] = STATE(26),
    [sym_parray] = STATE(26),
    [sym_barray] = STATE(26),
    [sym_mptuple] = STATE(26),
    [sym_ptuple] = STATE(26),
    [sym_btuple] = STATE(26),
    [sym_struct] = STATE(26),
    [sym_dict] = STATE(26),
    [sym_bytes] = STATE(39),
    [aux_sym_value_repeat1] = STATE(18),
    [aux_sym_mptuple_repeat1] = STATE(69),
    [aux_sym_struct_repeat1] = STATE(14),
    [sym__ws] = ACTIONS(143),
    [anon_sym_POUND] = ACTIONS(146),
    [anon_sym_nil] = ACTIONS(149),
    [anon_sym_true] = ACTIONS(149),
    [anon_sym_false] = ACTIONS(149),
    [sym_number] = ACTIONS(152),
    [sym_keyword] = ACTIONS(155),
    [anon_sym_AT] = ACTIONS(158),
    [anon_sym_LPAREN] = ACTIONS(161),
    [anon_sym_LBRACK] = ACTIONS(164),
    [anon_sym_LBRACE] = ACTIONS(167),
    [anon_sym_RBRACE] = ACTIONS(170),
    [sym_symbol] = ACTIONS(152),
    [anon_sym_DQUOTE] = ACTIONS(172),
    [sym_readermac] = ACTIONS(175),
  },
  [15] = {
    [sym_mvalue] = STATE(10),
    [sym__mraw_value] = STATE(47),
    [sym_comment] = STATE(47),
    [sym_constant] = STATE(47),
    [sym_string] = STATE(47),
    [sym_buffer] = STATE(47),
    [sym_parray] = STATE(47),
    [sym_barray] = STATE(47),
    [sym_mptuple] = STATE(47),
    [sym_ptuple] = STATE(54),
    [sym_btuple] = STATE(47),
    [sym_struct] = STATE(47),
    [sym_dict] = STATE(47),
    [sym_bytes] = STATE(39),
    [aux_sym_value_repeat1] = STATE(19),
    [aux_sym_mptuple_repeat1] = STATE(69),
    [aux_sym_mptuple_repeat2] = STATE(10),
    [sym__ws] = ACTIONS(96),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_nil] = ACTIONS(76),
    [anon_sym_true] = ACTIONS(76),
    [anon_sym_false] = ACTIONS(76),
    [sym_number] = ACTIONS(98),
    [sym_keyword] = ACTIONS(100),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(178),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
    [sym_symbol] = ACTIONS(98),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [sym_readermac] = ACTIONS(25),
  },
  [16] = {
    [sym_value] = STATE(53),
    [sym__raw_value] = STATE(26),
    [sym_comment] = STATE(26),
    [sym_constant] = STATE(26),
    [sym_string] = STATE(26),
    [sym_buffer] = STATE(26),
    [sym_parray] = STATE(26),
    [sym_barray] = STATE(26),
    [sym_mptuple] = STATE(26),
    [sym_ptuple] = STATE(26),
    [sym_btuple] = STATE(26),
    [sym_struct] = STATE(26),
    [sym_dict] = STATE(26),
    [sym_bytes] = STATE(39),
    [aux_sym_value_repeat1] = STATE(20),
    [aux_sym_mptuple_repeat1] = STATE(69),
    [sym__ws] = ACTIONS(180),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_nil] = ACTIONS(182),
    [anon_sym_true] = ACTIONS(182),
    [anon_sym_false] = ACTIONS(182),
    [sym_number] = ACTIONS(11),
    [sym_keyword] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
    [sym_symbol] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [sym_readermac] = ACTIONS(25),
  },
  [17] = {
    [sym__raw_value] = STATE(27),
    [sym_comment] = STATE(27),
    [sym_constant] = STATE(27),
    [sym_string] = STATE(27),
    [sym_buffer] = STATE(27),
    [sym_parray] = STATE(27),
    [sym_barray] = STATE(27),
    [sym_mptuple] = STATE(27),
    [sym_ptuple] = STATE(27),
    [sym_btuple] = STATE(27),
    [sym_struct] = STATE(27),
    [sym_dict] = STATE(27),
    [sym_bytes] = STATE(39),
    [aux_sym_value_repeat1] = STATE(55),
    [aux_sym_mptuple_repeat1] = STATE(69),
    [sym__ws] = ACTIONS(184),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_nil] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(9),
    [anon_sym_false] = ACTIONS(9),
    [sym_number] = ACTIONS(186),
    [sym_keyword] = ACTIONS(188),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
    [sym_symbol] = ACTIONS(186),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [sym_readermac] = ACTIONS(25),
  },
  [18] = {
    [sym__raw_value] = STATE(27),
    [sym_comment] = STATE(27),
    [sym_constant] = STATE(27),
    [sym_string] = STATE(27),
    [sym_buffer] = STATE(27),
    [sym_parray] = STATE(27),
    [sym_barray] = STATE(27),
    [sym_mptuple] = STATE(27),
    [sym_ptuple] = STATE(27),
    [sym_btuple] = STATE(27),
    [sym_struct] = STATE(27),
    [sym_dict] = STATE(27),
    [sym_bytes] = STATE(39),
    [aux_sym_value_repeat1] = STATE(55),
    [aux_sym_mptuple_repeat1] = STATE(69),
    [sym__ws] = ACTIONS(184),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_nil] = ACTIONS(29),
    [anon_sym_true] = ACTIONS(29),
    [anon_sym_false] = ACTIONS(29),
    [sym_number] = ACTIONS(186),
    [sym_keyword] = ACTIONS(188),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
    [sym_symbol] = ACTIONS(186),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [sym_readermac] = ACTIONS(25),
  },
  [19] = {
    [sym__mraw_value] = STATE(46),
    [sym_comment] = STATE(46),
    [sym_constant] = STATE(46),
    [sym_string] = STATE(46),
    [sym_buffer] = STATE(46),
    [sym_parray] = STATE(46),
    [sym_barray] = STATE(46),
    [sym_mptuple] = STATE(46),
    [sym_ptuple] = STATE(54),
    [sym_btuple] = STATE(46),
    [sym_struct] = STATE(46),
    [sym_dict] = STATE(46),
    [sym_bytes] = STATE(39),
    [aux_sym_value_repeat1] = STATE(55),
    [aux_sym_mptuple_repeat1] = STATE(69),
    [sym__ws] = ACTIONS(184),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_nil] = ACTIONS(76),
    [anon_sym_true] = ACTIONS(76),
    [anon_sym_false] = ACTIONS(76),
    [sym_number] = ACTIONS(190),
    [sym_keyword] = ACTIONS(192),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
    [sym_symbol] = ACTIONS(190),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [sym_readermac] = ACTIONS(25),
  },
  [20] = {
    [sym__raw_value] = STATE(27),
    [sym_comment] = STATE(27),
    [sym_constant] = STATE(27),
    [sym_string] = STATE(27),
    [sym_buffer] = STATE(27),
    [sym_parray] = STATE(27),
    [sym_barray] = STATE(27),
    [sym_mptuple] = STATE(27),
    [sym_ptuple] = STATE(27),
    [sym_btuple] = STATE(27),
    [sym_struct] = STATE(27),
    [sym_dict] = STATE(27),
    [sym_bytes] = STATE(39),
    [aux_sym_value_repeat1] = STATE(55),
    [aux_sym_mptuple_repeat1] = STATE(69),
    [sym__ws] = ACTIONS(184),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_nil] = ACTIONS(182),
    [anon_sym_true] = ACTIONS(182),
    [anon_sym_false] = ACTIONS(182),
    [sym_number] = ACTIONS(186),
    [sym_keyword] = ACTIONS(188),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
    [sym_symbol] = ACTIONS(186),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [sym_readermac] = ACTIONS(25),
  },
  [21] = {
    [sym__raw_value] = STATE(27),
    [sym_comment] = STATE(27),
    [sym_constant] = STATE(27),
    [sym_string] = STATE(27),
    [sym_buffer] = STATE(27),
    [sym_parray] = STATE(27),
    [sym_barray] = STATE(27),
    [sym_mptuple] = STATE(27),
    [sym_ptuple] = STATE(27),
    [sym_btuple] = STATE(27),
    [sym_struct] = STATE(27),
    [sym_dict] = STATE(27),
    [sym_bytes] = STATE(39),
    [aux_sym_value_repeat1] = STATE(55),
    [aux_sym_mptuple_repeat1] = STATE(69),
    [sym__ws] = ACTIONS(184),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_nil] = ACTIONS(76),
    [anon_sym_true] = ACTIONS(76),
    [anon_sym_false] = ACTIONS(76),
    [sym_number] = ACTIONS(186),
    [sym_keyword] = ACTIONS(188),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
    [sym_symbol] = ACTIONS(186),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [sym_readermac] = ACTIONS(25),
  },
  [22] = {
    [sym__raw_value] = STATE(27),
    [sym_comment] = STATE(27),
    [sym_constant] = STATE(27),
    [sym_string] = STATE(27),
    [sym_buffer] = STATE(27),
    [sym_parray] = STATE(27),
    [sym_barray] = STATE(27),
    [sym_mptuple] = STATE(27),
    [sym_ptuple] = STATE(27),
    [sym_btuple] = STATE(27),
    [sym_struct] = STATE(27),
    [sym_dict] = STATE(27),
    [sym_bytes] = STATE(39),
    [aux_sym_value_repeat1] = STATE(55),
    [aux_sym_mptuple_repeat1] = STATE(69),
    [sym__ws] = ACTIONS(184),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_nil] = ACTIONS(82),
    [anon_sym_true] = ACTIONS(82),
    [anon_sym_false] = ACTIONS(82),
    [sym_number] = ACTIONS(186),
    [sym_keyword] = ACTIONS(188),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
    [sym_symbol] = ACTIONS(186),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [sym_readermac] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(196), 1,
      sym__ws,
    STATE(24), 1,
      aux_sym_value_repeat2,
    ACTIONS(199), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(194), 10,
      ts_builtin_sym_end,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [28] = 4,
    ACTIONS(203), 1,
      sym__ws,
    STATE(24), 1,
      aux_sym_value_repeat2,
    ACTIONS(206), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(201), 10,
      ts_builtin_sym_end,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [56] = 4,
    ACTIONS(210), 1,
      sym__ws,
    STATE(24), 1,
      aux_sym_value_repeat2,
    ACTIONS(213), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(208), 10,
      ts_builtin_sym_end,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [84] = 4,
    ACTIONS(217), 1,
      sym__ws,
    STATE(25), 1,
      aux_sym_value_repeat2,
    ACTIONS(220), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(215), 10,
      ts_builtin_sym_end,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [112] = 4,
    ACTIONS(224), 1,
      sym__ws,
    STATE(23), 1,
      aux_sym_value_repeat2,
    ACTIONS(227), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(222), 10,
      ts_builtin_sym_end,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [140] = 2,
    ACTIONS(231), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(229), 11,
      ts_builtin_sym_end,
      sym__ws,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [163] = 2,
    ACTIONS(235), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(233), 11,
      ts_builtin_sym_end,
      sym__ws,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [186] = 2,
    ACTIONS(239), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(237), 11,
      ts_builtin_sym_end,
      sym__ws,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [209] = 2,
    ACTIONS(243), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(241), 11,
      ts_builtin_sym_end,
      sym__ws,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [232] = 2,
    ACTIONS(247), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(245), 11,
      ts_builtin_sym_end,
      sym__ws,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [255] = 2,
    ACTIONS(251), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(249), 11,
      ts_builtin_sym_end,
      sym__ws,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [278] = 2,
    ACTIONS(255), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(253), 11,
      ts_builtin_sym_end,
      sym__ws,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [301] = 2,
    ACTIONS(259), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(257), 11,
      ts_builtin_sym_end,
      sym__ws,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [324] = 2,
    ACTIONS(263), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(261), 11,
      ts_builtin_sym_end,
      sym__ws,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [347] = 2,
    ACTIONS(267), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(265), 11,
      ts_builtin_sym_end,
      sym__ws,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [370] = 2,
    ACTIONS(271), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(269), 11,
      ts_builtin_sym_end,
      sym__ws,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [393] = 2,
    ACTIONS(275), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(273), 11,
      ts_builtin_sym_end,
      sym__ws,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [416] = 2,
    ACTIONS(279), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(277), 11,
      ts_builtin_sym_end,
      sym__ws,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [439] = 2,
    ACTIONS(283), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(281), 11,
      ts_builtin_sym_end,
      sym__ws,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [462] = 2,
    ACTIONS(287), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(285), 11,
      ts_builtin_sym_end,
      sym__ws,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [485] = 2,
    ACTIONS(291), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(289), 11,
      ts_builtin_sym_end,
      sym__ws,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [508] = 2,
    ACTIONS(295), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(293), 11,
      ts_builtin_sym_end,
      sym__ws,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [531] = 4,
    ACTIONS(297), 1,
      sym__ws,
    STATE(24), 1,
      aux_sym_value_repeat2,
    ACTIONS(300), 7,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
    ACTIONS(302), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
  [556] = 4,
    ACTIONS(304), 1,
      sym__ws,
    STATE(45), 1,
      aux_sym_value_repeat2,
    ACTIONS(307), 7,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
    ACTIONS(309), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
  [581] = 4,
    ACTIONS(311), 1,
      sym__ws,
    STATE(48), 1,
      aux_sym_value_repeat2,
    ACTIONS(314), 7,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
    ACTIONS(316), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
  [606] = 4,
    ACTIONS(318), 1,
      sym__ws,
    STATE(24), 1,
      aux_sym_value_repeat2,
    ACTIONS(321), 7,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
    ACTIONS(323), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
  [631] = 3,
    ACTIONS(329), 1,
      aux_sym_constant_token1,
    ACTIONS(327), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(325), 8,
      sym__ws,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
  [654] = 3,
    ACTIONS(329), 1,
      aux_sym_constant_token1,
    ACTIONS(327), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(325), 8,
      sym__ws,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
  [677] = 3,
    ACTIONS(329), 1,
      aux_sym_constant_token1,
    ACTIONS(327), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(325), 8,
      sym__ws,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [700] = 3,
    ACTIONS(329), 1,
      aux_sym_constant_token1,
    ACTIONS(327), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(325), 8,
      ts_builtin_sym_end,
      sym__ws,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
  [723] = 2,
    ACTIONS(331), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(170), 8,
      sym__ws,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [743] = 2,
    ACTIONS(335), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
    ACTIONS(333), 8,
      sym__ws,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
  [763] = 5,
    ACTIONS(337), 1,
      sym__ws,
    ACTIONS(344), 1,
      sym_readermac,
    STATE(55), 1,
      aux_sym_value_repeat1,
    ACTIONS(340), 6,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
    ACTIONS(342), 6,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
  [789] = 3,
    ACTIONS(329), 1,
      aux_sym_constant_token1,
    ACTIONS(325), 7,
      sym__ws,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
    ACTIONS(327), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
  [811] = 4,
    ACTIONS(351), 1,
      anon_sym_LPAREN,
    ACTIONS(354), 1,
      sym_readermac,
    ACTIONS(347), 6,
      sym__ws,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
    ACTIONS(349), 6,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
  [834] = 2,
    ACTIONS(347), 7,
      sym__ws,
      anon_sym_POUND,
      sym_keyword,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
    ACTIONS(349), 7,
      anon_sym_nil,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_AT,
      sym_symbol,
      sym_readermac,
  [853] = 8,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    STATE(30), 1,
      sym_struct,
    STATE(31), 1,
      sym_bytes,
    STATE(38), 1,
      sym_ptuple,
    STATE(42), 1,
      sym_btuple,
  [878] = 4,
    ACTIONS(357), 1,
      aux_sym_escape_token1,
    ACTIONS(359), 1,
      anon_sym_DQUOTE,
    ACTIONS(361), 1,
      aux_sym_bytes_token1,
    STATE(61), 2,
      sym_escape,
      aux_sym_bytes_repeat1,
  [892] = 4,
    ACTIONS(363), 1,
      aux_sym_escape_token1,
    ACTIONS(366), 1,
      anon_sym_DQUOTE,
    ACTIONS(368), 1,
      aux_sym_bytes_token1,
    STATE(61), 2,
      sym_escape,
      aux_sym_bytes_repeat1,
  [906] = 4,
    ACTIONS(357), 1,
      aux_sym_escape_token1,
    ACTIONS(371), 1,
      anon_sym_DQUOTE,
    ACTIONS(373), 1,
      aux_sym_bytes_token1,
    STATE(60), 2,
      sym_escape,
      aux_sym_bytes_repeat1,
  [920] = 4,
    ACTIONS(375), 1,
      aux_sym_escape_token2,
    ACTIONS(377), 1,
      aux_sym_escape_token3,
    ACTIONS(379), 1,
      aux_sym_escape_token4,
    ACTIONS(381), 1,
      aux_sym_escape_token5,
  [933] = 2,
    ACTIONS(385), 1,
      aux_sym_bytes_token1,
    ACTIONS(383), 2,
      aux_sym_escape_token1,
      anon_sym_DQUOTE,
  [941] = 2,
    ACTIONS(389), 1,
      aux_sym_bytes_token1,
    ACTIONS(387), 2,
      aux_sym_escape_token1,
      anon_sym_DQUOTE,
  [949] = 2,
    ACTIONS(393), 1,
      aux_sym_bytes_token1,
    ACTIONS(391), 2,
      aux_sym_escape_token1,
      anon_sym_DQUOTE,
  [957] = 3,
    ACTIONS(395), 1,
      anon_sym_LPAREN,
    ACTIONS(397), 1,
      sym_readermac,
    STATE(67), 1,
      aux_sym_mptuple_repeat1,
  [967] = 2,
    ACTIONS(402), 1,
      aux_sym_bytes_token1,
    ACTIONS(400), 2,
      aux_sym_escape_token1,
      anon_sym_DQUOTE,
  [975] = 3,
    ACTIONS(404), 1,
      anon_sym_LPAREN,
    ACTIONS(406), 1,
      sym_readermac,
    STATE(67), 1,
      aux_sym_mptuple_repeat1,
  [985] = 1,
    ACTIONS(408), 1,
      sym_hex,
  [989] = 1,
    ACTIONS(410), 1,
      sym_hex,
  [993] = 1,
    ACTIONS(412), 1,
      sym_hex,
  [997] = 1,
    ACTIONS(414), 1,
      sym_hex,
  [1001] = 1,
    ACTIONS(416), 1,
      sym_hex,
  [1005] = 1,
    ACTIONS(418), 1,
      sym_hex,
  [1009] = 1,
    ACTIONS(420), 1,
      sym_hex,
  [1013] = 1,
    ACTIONS(422), 1,
      sym_hex,
  [1017] = 1,
    ACTIONS(424), 1,
      aux_sym_comment_token1,
  [1021] = 1,
    ACTIONS(426), 1,
      ts_builtin_sym_end,
  [1025] = 1,
    ACTIONS(428), 1,
      sym_hex,
  [1029] = 1,
    ACTIONS(430), 1,
      sym_hex,
  [1033] = 1,
    ACTIONS(432), 1,
      sym_hex,
  [1037] = 1,
    ACTIONS(434), 1,
      sym_hex,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(23)] = 0,
  [SMALL_STATE(24)] = 28,
  [SMALL_STATE(25)] = 56,
  [SMALL_STATE(26)] = 84,
  [SMALL_STATE(27)] = 112,
  [SMALL_STATE(28)] = 140,
  [SMALL_STATE(29)] = 163,
  [SMALL_STATE(30)] = 186,
  [SMALL_STATE(31)] = 209,
  [SMALL_STATE(32)] = 232,
  [SMALL_STATE(33)] = 255,
  [SMALL_STATE(34)] = 278,
  [SMALL_STATE(35)] = 301,
  [SMALL_STATE(36)] = 324,
  [SMALL_STATE(37)] = 347,
  [SMALL_STATE(38)] = 370,
  [SMALL_STATE(39)] = 393,
  [SMALL_STATE(40)] = 416,
  [SMALL_STATE(41)] = 439,
  [SMALL_STATE(42)] = 462,
  [SMALL_STATE(43)] = 485,
  [SMALL_STATE(44)] = 508,
  [SMALL_STATE(45)] = 531,
  [SMALL_STATE(46)] = 556,
  [SMALL_STATE(47)] = 581,
  [SMALL_STATE(48)] = 606,
  [SMALL_STATE(49)] = 631,
  [SMALL_STATE(50)] = 654,
  [SMALL_STATE(51)] = 677,
  [SMALL_STATE(52)] = 700,
  [SMALL_STATE(53)] = 723,
  [SMALL_STATE(54)] = 743,
  [SMALL_STATE(55)] = 763,
  [SMALL_STATE(56)] = 789,
  [SMALL_STATE(57)] = 811,
  [SMALL_STATE(58)] = 834,
  [SMALL_STATE(59)] = 853,
  [SMALL_STATE(60)] = 878,
  [SMALL_STATE(61)] = 892,
  [SMALL_STATE(62)] = 906,
  [SMALL_STATE(63)] = 920,
  [SMALL_STATE(64)] = 933,
  [SMALL_STATE(65)] = 941,
  [SMALL_STATE(66)] = 949,
  [SMALL_STATE(67)] = 957,
  [SMALL_STATE(68)] = 967,
  [SMALL_STATE(69)] = 975,
  [SMALL_STATE(70)] = 985,
  [SMALL_STATE(71)] = 989,
  [SMALL_STATE(72)] = 993,
  [SMALL_STATE(73)] = 997,
  [SMALL_STATE(74)] = 1001,
  [SMALL_STATE(75)] = 1005,
  [SMALL_STATE(76)] = 1009,
  [SMALL_STATE(77)] = 1013,
  [SMALL_STATE(78)] = 1017,
  [SMALL_STATE(79)] = 1021,
  [SMALL_STATE(80)] = 1025,
  [SMALL_STATE(81)] = 1029,
  [SMALL_STATE(82)] = 1033,
  [SMALL_STATE(83)] = 1037,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mptuple_repeat2, 2, 0, 0), SHIFT_REPEAT(19),
  [109] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mptuple_repeat2, 2, 0, 0), SHIFT_REPEAT(78),
  [112] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_mptuple_repeat2, 2, 0, 0), SHIFT_REPEAT(49),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_mptuple_repeat2, 2, 0, 0), SHIFT_REPEAT(47),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mptuple_repeat2, 2, 0, 0), SHIFT_REPEAT(47),
  [121] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_mptuple_repeat2, 2, 0, 0), SHIFT_REPEAT(59),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mptuple_repeat2, 2, 0, 0), SHIFT_REPEAT(5),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_mptuple_repeat2, 2, 0, 0),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mptuple_repeat2, 2, 0, 0), SHIFT_REPEAT(6),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mptuple_repeat2, 2, 0, 0), SHIFT_REPEAT(2),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mptuple_repeat2, 2, 0, 0), SHIFT_REPEAT(62),
  [138] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_mptuple_repeat2, 2, 0, 0), SHIFT_REPEAT(57),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [149] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [152] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [158] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [161] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [164] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [167] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0),
  [172] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [175] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 3, 0, 2),
  [196] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_value, 3, 0, 2), SHIFT(24),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 3, 0, 2),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_value_repeat2, 2, 0, 0),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_repeat2, 2, 0, 0), SHIFT_REPEAT(24),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_value_repeat2, 2, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 2, 0, 0),
  [210] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_value, 2, 0, 0), SHIFT(24),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 2, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [217] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_value, 1, 0, 0), SHIFT(25),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 2, 0, 2),
  [224] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_value, 2, 0, 2), SHIFT(23),
  [227] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 2, 0, 2),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 3, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 3, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bytes, 3, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bytes, 3, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 2, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dict, 2, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_buffer, 2, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_buffer, 2, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ptuple, 2, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ptuple, 2, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_btuple, 2, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_btuple, 2, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 2, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 2, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mptuple, 3, 0, 1),
  [259] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mptuple, 3, 0, 1),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bytes, 2, 0, 0),
  [263] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bytes, 2, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 2, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constant, 2, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parray, 2, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parray, 2, 0, 0),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [275] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ptuple, 3, 0, 4),
  [279] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ptuple, 3, 0, 4),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_btuple, 3, 0, 0),
  [283] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_btuple, 3, 0, 0),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_barray, 2, 0, 0),
  [287] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_barray, 2, 0, 0),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [291] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mptuple, 4, 0, 1),
  [295] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mptuple, 4, 0, 1),
  [297] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_mvalue, 3, 0, 2), SHIFT(24),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mvalue, 3, 0, 2),
  [302] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mvalue, 3, 0, 2),
  [304] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_mvalue, 2, 0, 2), SHIFT(45),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mvalue, 2, 0, 2),
  [309] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mvalue, 2, 0, 2),
  [311] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_mvalue, 1, 0, 0), SHIFT(48),
  [314] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mvalue, 1, 0, 0),
  [316] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mvalue, 1, 0, 0),
  [318] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_mvalue, 2, 0, 0), SHIFT(24),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mvalue, 2, 0, 0),
  [323] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mvalue, 2, 0, 0),
  [325] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 1, 0, 0),
  [327] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constant, 1, 0, 0),
  [329] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [331] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_struct_repeat1, 2, 0, 0),
  [333] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__mraw_value, 1, 0, 5),
  [335] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__mraw_value, 1, 0, 5),
  [337] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 2, 0, 3), SHIFT_REPEAT(55),
  [340] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 2, 0, 3),
  [342] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 3),
  [344] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 3), SHIFT_REPEAT(58),
  [347] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 1, 0, 1),
  [349] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 1, 0, 1),
  [351] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 1, 0, 1), REDUCE(aux_sym_mptuple_repeat1, 1, 0, 0),
  [354] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 1, 0, 1), REDUCE(aux_sym_mptuple_repeat1, 1, 0, 0),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [361] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [363] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bytes_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [366] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_bytes_repeat1, 2, 0, 0),
  [368] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_bytes_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [373] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [383] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape, 2, 0, 0),
  [385] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape, 2, 0, 0),
  [387] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape, 6, 0, 0),
  [389] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape, 6, 0, 0),
  [391] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape, 8, 0, 0),
  [393] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape, 8, 0, 0),
  [395] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_mptuple_repeat1, 2, 0, 0),
  [397] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mptuple_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [400] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape, 4, 0, 0),
  [402] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape, 4, 0, 0),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [406] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [408] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [410] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [412] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [414] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [416] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [418] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [420] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [422] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [424] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [426] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [428] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [430] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [432] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [434] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_janet(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym__symchars,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
